parameters:
  Artifacts: []
  ServiceDirectory: not-specified

jobs:
  - job: "Analyze"
    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: "$(OSVmImage)"

    steps:
      - template: /eng/common/pipelines/templates/steps/analyze-pkg-props.yml
        parameters:
            ServiceDirectory: ${{parameters.ServiceDirectory}}
            Artifacts: ${{parameters.Artifacts}}
